# Generated by Django 5.1.1 on 2024-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=225)),
                ('student_secondname', models.CharField(max_length=225)),
                ('student_number', models.IntegerField()),
                ('student_address', models.EmailField(max_length=225)),
                ('student_fee', models.IntegerField()),
            ],
        ),
    ]
