# Generated by Django 5.1.1 on 2024-09-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='student_secondname',
            new_name='student_lastname',
        ),
    ]
